# Generated by Django 4.1.2 on 2024-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_remove_location_menu'),
        ('product', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(related_name='categories', to='location.location'),
        ),
    ]
