# Generated by Django 4.1.2 on 2024-04-17 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_webmenuuser_system_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
