# Generated by Django 4.1.2 on 2024-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_loginhistory_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='account_email',
            field=models.CharField(db_index=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
